org: unfocused
app: apollo-lambda
service: apollo-lambda
provider:
  name: aws
  runtime: nodejs16.x
  httpApi:
    cors: true
  environment:
    MONGODB_URI: ${param:mongodb_uri}
functions:
  graphql:
    handler: index.graphqlHandler # highlight-line
    events:
      - httpApi:
          path: /
          method: POST
      - httpApi:
          path: /
          method: GET